config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'invoices#index'

  resources :invoices
  resources :invoice_status

end

app/models/invoice_item.rb
class InvoiceItem < ActiveRecord::Base
  
end

app/models/invoice_status.rb
class InvoiceStatus < ActiveRecord::Base
end

app/models/invoice_summary.rb
class InvoiceSummary < ActiveRecord::Base
  has_many :invoice_items
  has_many :invoice_statuses

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoice_status_controller.rb
class InvoiceStatusController < ApplicationController
  skip_before_filter :authenticate_user!
  protect_from_forgery :except => :create

  def index

  end

  def create
    render nothing: true

    invoiceStatus = InvoiceStatus.new
    data_json = JSON.parse request.body.read
    invoiceStatus.notes = data_json
    invoiceStatus.save

  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index
    @invoiceSummaries = InvoiceSummary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoiceSummaries }
    end

  end

  def new
    if !params["simple"].nil?
      render "new_simple"
    elsif !params["bulk"].nil?
      render "new_bulk"
    end
  end

  def show
    @invoice_summary = InvoiceSummary.find_by_id(params[:id])
  end

  def create

    invoiceSummary = InvoiceSummary.new
    invoiceSummary.customer_email = params["invoicecustomeremail"]
    invoiceSummary.title = params["invoicecustomeremail"]
    invoiceSummary.due_date = params["invoiceduedate"]
    invoiceSummary.customer_name = params["invoicecustomername"]
    invoiceSummary.atpay_invoice_uuid = params["atpay_invoice_uuid"]
    invoiceSummary.created_at = Time.now
    invoiceSummary.save

    invoiceId = invoiceSummary.id

    params.each do |key, value|
      if key.to_s.include? "invoiceitem"
        invoiceItemArray = value.split(',')
        invoiceItem = InvoiceItem.new
        invoiceItem.invoice_summary_id = invoiceSummary.id

        #Replace $ so that amount is added properly and then multiply against quantity.
        invoiceItem.amount = invoiceItemArray[2].gsub('$','').to_f * invoiceItemArray[3].to_i

        invoiceItem.created_at = Time.now
        invoiceItem.date = invoiceItemArray[4]
        invoiceItem.name = invoiceItemArray[0]
        invoiceItem.description = invoiceItemArray[1]
        invoiceItem.quantity = invoiceItemArray[3]
        invoiceItem.save
      end

    end

      redirect_to "/invoices"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/invoice_status_helper.rb
module InvoiceStatusHelper
end

app/views/invoices/index.html.erb
<h1>Invoices</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Customer Name</th>
    <th>Total Due</th>
    <th>Due Date</th>
  </tr>
  </thead>
  <tbody>
  <% @invoiceSummaries.each do |invoiceSummary| %>
      <tr>
        <td><%= invoiceSummary.id %></td>
        <td><%= link_to invoiceSummary.title, invoice_path(invoiceSummary) %></td>
        <td><%= invoiceSummary.customer_name %></td>
        <td><%= number_to_currency(invoiceSummary.invoice_items.sum(:amount), :precision => 2) %></td>
        <td><%= invoiceSummary.created_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New', new_invoice_path, :class => 'btn btn-primary' %>

app/views/invoices/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <legend>Invoice Title:<span id="invoicetitledisplay"></span></legend>
    </div>
    <div class="col-sm-6" style="text-align: right;">
      <legend>Invoice Number:<span id="invoicenumberdisplay">00001</span></legend>
    </div>
    <%= form_tag("/invoices", method: "post", id: "atpay-invoicing") do %>
        <input type="hidden" value="0" name="atpay_invoice_uuid" id="atpay_invoice_uuid" >
        <div class="col-sm-4"><input type="text" class="form-control" id="invoicetitle" placeholder="Invoice Title" name="invoicetitle"> </div>
        <div class="col-sm-4"><input type="text" class="form-control" id="invoicenumber" name="invoicenumber" placeholder="00001"></div>
        <div class="col-sm-4"><input type="text" class="form-control" id="invoiceduedate" name="invoiceduedate" placeholder="Due Date"></div>
        <div class="col-sm-12">&nbsp;</div>
        <div class="col-sm-6"><input type="text" class="form-control" id="invoicecustomername" name="invoicecustomername" placeholder="Customer Name"></div>
        <div class="col-sm-6"><input type="text" class="form-control" id="invoicecustomeremail" name="invoicecustomeremail" placeholder="Customer Email"></div>
        <div class="col-sm-12"><hr></div>
        <!-- panel preview -->
        <div class="col-sm-5">
          <h4>Add Invoice Item:</h4>
          <div class="panel panel-default">
            <div class="panel-body form-horizontal payment-form">
              <div class="form-group">
                <label for="name" class="col-sm-3 control-label">Name</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" id="name" name="name">
                </div>
              </div>
              <div class="form-group">
                <label for="description" class="col-sm-3 control-label">Description</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" id="description" name="description">
                </div>
              </div>
              <div class="form-group">
                <label for="amount" class="col-sm-3 control-label">Amount</label>
                <div class="col-sm-9">
                  <input type="number" class="form-control" id="amount" name="amount">
                </div>
              </div>
              <div class="form-group">
                <label for="quantity" class="col-sm-3 control-label">Quantity</label>
                <div class="col-sm-9">
                  <select class="form-control" id="quantity" name="quantity">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                </div>
              </div>
              <div class="form-group">
                <label for="date" class="col-sm-3 control-label">Date</label>
                <div class="col-sm-9">
                  <input type="date" class="form-control" id="date" name="date">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-12 text-right">
                  <button type="button" class="btn btn-default preview-add-button">
                    <span class="glyphicon glyphicon-plus"></span> Add
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- / panel preview -->
        <div class="col-sm-7">
          <h4>Preview:</h4>
          <div class="row">
            <div class="col-xs-12">
              <div class="table-responsive">
                <table class="table preview-table">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Quantity</th>
                    <th>Date</th>
                  </tr>
                  </thead>
                  <tbody></tbody> <!-- preview content goes here-->
                </table>
              </div>
            </div>
          </div>
          <div class="row text-right">
            <div class="col-xs-12">
              <h5>Subtotal: <strong><span class="preview-subtotal"></span></strong></h5>
            </div>
          </div>
          <div class="row text-right">
            <div class="col-xs-12">
              <h5>Sales Tax: <strong><span class="preview-tax">5.215%</span></strong></h5>
            </div>
          </div>
          <div class="row text-right">
            <div class="col-xs-12">
              <h4>Total: <strong><span class="preview-total"></span></strong></h4>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <hr style="border:1px dashed #dddddd;">
              <button type="submit" class="btn btn-primary btn-block">Submit all and request payment</button>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/invoices/new_bulk.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/invoice_navigation' %>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <!--<legend>Invoice Title:<span id="invoicetitledisplay"></span></legend>-->
    </div>
    <div class="col-sm-6" style="text-align: right;">
      &nbsp;
      <!-- <legend>Invoice Number:<span id="invoicenumberdisplay">00001</span></legend> -->
    </div>
    <%= form_tag("/invoices", method: "post", id: "atpay-invoicing") do %>
        <input type="hidden" value="0" name="atpay_invoice_uuid" id="atpay_invoice_uuid" >
        <div class="col-sm-4">&nbsp;</div>
        <div class="col-sm-8">
          <div class="col-lg-6 col-sm-6 col-12">
            <h4>Input Groups</h4>
            <div class="input-group">
                <span class="input-group-btn">
                    <span class="btn btn-primary btn-file">
                        Browse&hellip; <input type="file" multiple>
                    </span>
                </span>
              <input type="text" class="form-control" readonly>
            </div>
          </div>
        </div>
        <div class="col-sm-12"><hr></div>
        <div class="col-sm-12">
            <div class="col-sm-4">&nbsp;</div>
            <div class="col-sm-4"><button type="submit" class="btn btn-primary btn-block">Submit all and request payment</button></div>
            <div class="col-sm-4">&nbsp;</div>
        </div>
        <!-- panel preview -->
        <% if false %>
            <div class="col-sm-5">
              <h4>Add Invoice Item:</h4>
              <div class="panel panel-default">
                <div class="panel-body form-horizontal payment-form">
                  <div class="form-group">
                    <label for="name" class="col-sm-3 control-label">Name</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" id="name" name="name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="description" class="col-sm-3 control-label">Description</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" id="description" name="description">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="amount" class="col-sm-3 control-label">Amount</label>
                    <div class="col-sm-9">
                      <input type="number" class="form-control" id="amount" name="amount">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="quantity" class="col-sm-3 control-label">Quantity</label>
                    <div class="col-sm-9">
                      <select class="form-control" id="quantity" name="quantity">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="date" class="col-sm-3 control-label">Date</label>
                    <div class="col-sm-9">
                      <input type="date" class="form-control" id="date" name="date">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-12 text-right">
                      <button type="button" id="btnPreview" name="btnPreview" class="btn btn-default preview-add-button">
                        <span class="glyphicon glyphicon-plus"></span> Add
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div> <!-- / panel preview -->
            <div class="col-sm-7">
              <h4>Preview:</h4>
              <div class="row">
                <div class="col-xs-12">
                  <div class="table-responsive">
                    <table class="table preview-table">
                      <thead>
                      <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Amount</th>
                        <th>Date</th>
                      </tr>
                      </thead>
                      <tbody></tbody> <!-- preview content goes here-->
                    </table>
                  </div>
                </div>
              </div>
              <div class="row text-right">
                <div class="col-xs-12">
                  <h5>Subtotal: <strong><span class="preview-subtotal"></span></strong></h5>
                </div>
              </div>
              <div class="row text-right">
                <div class="col-xs-12">
                  <h5>Sales Tax @5.12%: <strong><span class="preview-tax"></span></strong></h5>
                </div>
              </div>
              <div class="row text-right">
                <div class="col-xs-12">
                  <h4>Total: <strong><span class="preview-total"></span></strong></h4>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12">
                  <hr style="border:1px dashed #dddddd;">

                </div>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/invoices/new_simple.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/invoice_navigation' %>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <!--<legend>Invoice Title:<span id="invoicetitledisplay"></span></legend>-->
    </div>
    <div class="col-sm-6" style="text-align: right;">
      &nbsp;
      <!-- <legend>Invoice Number:<span id="invoicenumberdisplay">00001</span></legend> -->
    </div>
    <%= form_tag("/invoices", method: "post", id: "atpay-invoicing") do %>
        <input type="hidden" value="0" name="atpay_invoice_uuid" id="atpay_invoice_uuid" >
        <div class="col-sm-4"><input type="text" class="form-control" id="invoicetitle" placeholder="Invoice Title" name="invoicetitle"> </div>
        <div class="col-sm-4"><input type="text" class="form-control" id="invoicecustomername" name="invoicecustomername" placeholder="Customer Name"></div>
        <div class="col-sm-4"><input type="text" class="form-control" id="invoicecustomeremail" name="invoicecustomeremail" placeholder="Customer Email"></div>
        <div class="col-sm-12"><hr></div>
        <div class="col-sm-4"><input type="text" class="form-control" id="invoiceamount" placeholder="Invoice Amount" name="invoiceamount"> </div>
        <div class="col-sm-8"><button type="submit" class="btn btn-primary btn-block">Submit all and request payment</button></div>


        <!-- panel preview -->
        <% if false %>
        <div class="col-sm-5">
          <h4>Add Invoice Item:</h4>
          <div class="panel panel-default">
            <div class="panel-body form-horizontal payment-form">
              <div class="form-group">
                <label for="name" class="col-sm-3 control-label">Name</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" id="name" name="name">
                </div>
              </div>
              <div class="form-group">
                <label for="description" class="col-sm-3 control-label">Description</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" id="description" name="description">
                </div>
              </div>
              <div class="form-group">
                <label for="amount" class="col-sm-3 control-label">Amount</label>
                <div class="col-sm-9">
                  <input type="number" class="form-control" id="amount" name="amount">
                </div>
              </div>
              <div class="form-group">
                <label for="quantity" class="col-sm-3 control-label">Quantity</label>
                <div class="col-sm-9">
                  <select class="form-control" id="quantity" name="quantity">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                </div>
              </div>
              <div class="form-group">
                <label for="date" class="col-sm-3 control-label">Date</label>
                <div class="col-sm-9">
                  <input type="date" class="form-control" id="date" name="date">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-12 text-right">
                  <button type="button" id="btnPreview" name="btnPreview" class="btn btn-default preview-add-button">
                    <span class="glyphicon glyphicon-plus"></span> Add
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- / panel preview -->
        <div class="col-sm-7">
          <h4>Preview:</h4>
          <div class="row">
            <div class="col-xs-12">
              <div class="table-responsive">
                <table class="table preview-table">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Amount</th>
                    <th>Date</th>
                  </tr>
                  </thead>
                  <tbody></tbody> <!-- preview content goes here-->
                </table>
              </div>
            </div>
          </div>
          <div class="row text-right">
            <div class="col-xs-12">
              <h5>Subtotal: <strong><span class="preview-subtotal"></span></strong></h5>
            </div>
          </div>
          <div class="row text-right">
            <div class="col-xs-12">
              <h5>Sales Tax @5.12%: <strong><span class="preview-tax"></span></strong></h5>
            </div>
          </div>
          <div class="row text-right">
            <div class="col-xs-12">
              <h4>Total: <strong><span class="preview-total"></span></strong></h4>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <hr style="border:1px dashed #dddddd;">

            </div>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/invoices/show.html.erb
<h1>Invoice Summary</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Customer Name</th>
    <th>Total Due</th>
    <th>Due Date</th>
  </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @invoice_summary.id %></td>
        <td><%= @invoice_summary.title %></td>
        <td><%= @invoice_summary.customer_name %></td>
        <td><%= number_to_currency(@invoice_summary.invoice_items.sum(:amount), :precision => 2) %></td>
        <td><%= @invoice_summary.created_at %></td>
      </tr>
  </tbody>
</table>
<hr />
<h3>Invoice Details</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Amount</th>
  </tr>
  </thead>
  <tbody>
  <% @invoice_summary.invoice_items.each do |invoiceItem| %>
      <tr>
        <td><%= invoiceItem.id %></td>
        <td><%= invoiceItem.name %></td>
        <td><%= invoiceItem.description %></td>
        <td><%= invoiceItem.quantity %></td>
        <td><%= number_to_currency(invoiceItem.amount, :precision => 2) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atpayinvoicing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<script type="text/javascript" src="https://dashboard.atpay.com/sdk/v3.js"></script>
  <%= render 'shared/navigation' %>
  <div id="main-container" class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>

  </body>
  </html>

app/views/shared/_invoice_navigation.html.erb
<div class="col-sm-12" style="text-align: center">
  <%= link_to 'Standard', new_invoice_path, :class => 'btn btn-primary' %> <%= link_to 'Simple', new_invoice_path + "?simple=true", :class => 'btn btn-primary' %>  <%= link_to 'Bulk Upload', new_invoice_path + "?bulk=true", :class => 'btn btn-primary' %>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-custom" role="navigation">
  <div class="container">
        <div class="navbar-header" style="width: 100%; vertical-align: top;">
            <div class="col-md-4">
              <img class="header_logo" src= "<%= asset_path('atpay-logo.png') %>" />
            </div>
            <div class="col-md-6">
              <h3 style="margin-top: 10px; margin-bottom: 5px">Invoicing Application</h3>
            </div>
            <div class="col-md-2" style="text-align: right">
              <a class="navbar-brand" href="/">Invoices</a>
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "navbar-brand") %>
                <% else %>
                  <%= link_to('Login', new_user_session_path, :class => "navbar-brand")  %>
                <% end %>
            </div>
        </div>
  <div>
</nav>